name: BanName
version: 1.0.0
main: nu.granskogen.spela.BanName.BanName
author: Bingoo

commands:
  banname:
    description: Ban a name but not the uuid, automaticly kicks the player from the server.
  unbanname:
    description: Unnban a player name.
  checkname:
    description: Check if a player name is banned.