database:
  host: 'localhost'
  database: 'granskogen'
  username: 'rasmus'
  password: 'PI=3,141592'

messages:
  kickReason: "&cDitt namn är inte tillåtet på Granskogen. Du är välkommen tillbaka när du har bytt namn."
  operatorSuccessMessage: "&aNamnet &2{name} &aär nu bannlyst från servern."
  unban: "&aNamnet &2{name} &aär nu inte bannlyst från servern."
  banMessage:
      layout:
      - ''
      - '&8&m+------------&8[&4&lNamn Bannlyst&8]&m------------+'
      - ''
      - '&2&l» &a&lBannlyst av: &f%OPERATOR%'
      - ''
      - '&2&l» &a&lAnledning: &fDitt namn är inte tillåtet på Granskogen.'
      - 'Du är välkommen tillbaka när du har bytt namn.'
      - ''
      - '&2&l» &a&lDiscord: &fwww.granskogen.nu/discord'
      - '&2&l» &a&lMail: &fsupport@granskogen.nu'
      - ''
      - '&8&m+----------------------------------------+'
  sytax:
    banName: "&7Syntax: /banName <spelarnamn>"
    unbanName: "&7Syntax: /unbanName <spelarnamn>"
  error:
    noPermission: "&cÅtkomst nekad!"
    alreadyBanned: "&cNamnet är redan bannlyst."
    notBanned: "&cNamnet är inte bannlyst."
    SQL: "&cSQL fel. Kontakta ledningen."
    statusBanned: "&cNamnet &4{name} &cär bannlyst."
    statusNotBanned: "&aNamnet &2{name} &aär inte bannlyst."